# 自定义配置文件
header:
  # 是否需要精确匹配
  accurate: false
  # 表头颜色
  bgColor:
  # 表头文字格式
  pattern:
  # 表头样式
  style:
    - NONE
    - THIN
  # 表头字体颜色
  fontColor:
  # 是否需要解析
  needParse: false
  # 范围
  rowRange: 1


content:
  titleFeature:
    color:
    pattern:
      - .*(?i)(船    名).*
    style:
     # - THIN
     # - NONE
  # 标题中需要忽略的列
  ignoreColumn:
    - .*(?i)(IRIS).*
  # 通用属性
  column:
    - vesselName(1)
    - carrierVoyageNo(1)
    - vesselCode(1)
    - shippingAgentCode(1)
    - terminalVoyageNo(1)
    - etd(1)
    - vgmCutOffTime(1)
    - portTerminalOfBerthingName(1)
    - oogSiCutOffTime(1)
  # 可变属性
  special:
    - 开航
    - VGM

tail:
  # 是否需要精确匹配
  accurate: false
  # 表尾颜色
  bgColor:
  # 表尾格式
  pattern:
  # 表尾样式
  style:
    - NONE
    - THIN
  # 表尾字体颜色
  fontColor:
  # 是否需要解析
  needParse: false
  #范围
  rowRange: 1